# Generated by Django 4.1.3 on 2023-09-05 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
