# Generated by Django 4.1.3 on 2023-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_task_task_alter_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
